# Generated by Django 6.0.6 on 2026-06-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['tab', 'subcategory', 'sort_order', 'name']},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='badge',
            field=models.CharField(blank=True, choices=[('', 'None'), ('POPULAR', 'Popular'), ('BESTSELLER', 'Bestseller'), ('PREMIUM', 'Premium'), ('NEW', 'New'), ('SPECIAL', 'Special')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Emoji (e.g. 🍸) or leave blank.', max_length=10),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide from menu without deleting.'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='price2',
            field=models.CharField(blank=True, default='', help_text='Second price (750ml / Bottle / Kothey / Large).', max_length=30),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='price3',
            field=models.CharField(blank=True, default='', help_text='Jhol price (MO:MO only).', max_length=30),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='price4',
            field=models.CharField(blank=True, default='', help_text='Chilly price (MO:MO only).', max_length=30),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='quote',
            field=models.CharField(blank=True, default='', help_text='Italic tagline shown under the name (mocktails / cocktails).', max_length=200),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('spirits', 'Spirits'), ('wine', 'Wine'), ('shots', 'Shots'), ('beers', 'Beer'), ('espresso', 'Espresso Based'), ('ice_espresso', 'Ice Espresso'), ('frappes', 'Frappes'), ('alternatives', 'Hot & Cold Alternatives'), ('milkshakes', 'Milkshakes'), ('lassi', 'Lassi'), ('matcha', 'Matcha'), ('juices', 'Fresh Juices'), ('tea', 'Tea'), ('salads', 'Salads'), ('gravy', 'Gravy with Rice'), ('rice_bowl', 'Rice Bowl'), ('veg_snacks', 'Veg Snacks'), ('nonveg_snacks', 'Non-Veg Snacks'), ('specials', "Chef's Specials"), ('sizzler', 'Sizzler'), ('burgers', 'Burgers & Sandwiches'), ('chowmien', 'Chowmien'), ('noodles', 'Noodles'), ('pizza', 'Pizza'), ('pasta', 'Pasta'), ('momo', 'MO:MO')], default='', help_text='Required for Bar, Café, and Food items to place them in the right section.', max_length=20),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='tab',
            field=models.CharField(choices=[('smoke', 'Hookah / Smoke'), ('mocktails', 'Mocktails'), ('cocktails', 'Cocktails'), ('bar', 'Bar'), ('cafe', 'Café'), ('food', 'Food')], default='smoke', max_length=20),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.CharField(help_text='Main price (or 30ml / Glass / Steam / Small).', max_length=30),
        ),
    ]
