# Generated by Django 6.0.6 on 2026-06-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_menuitem_options_remove_menuitem_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image_url', models.URLField(help_text='Paste a full image URL (e.g. from Unsplash or your own host).', max_length=500)),
                ('category', models.CharField(choices=[('lounge', 'Lounge'), ('hookah', 'Hookah'), ('drinks', 'Drinks'), ('events', 'Events'), ('food', 'Food'), ('cafe', 'Café')], default='lounge', max_length=20)),
                ('is_large', models.BooleanField(default=False, help_text='Makes this image span two columns in the grid (featured/wide layout).')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from gallery without deleting.')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
