# Generated by Django 6.0.6 on 2026-06-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image from your computer.', null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Or paste an external URL. If both are set, the uploaded image takes priority.', max_length=500),
        ),
    ]
