# Generated by Django 6.0.6 on 2026-06-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_galleryimage_image_alter_galleryimage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('spirits', 'Spirits'), ('wine', 'Wine'), ('shots', 'Shots'), ('beers', 'Beer'), ('espresso', 'Espresso Based'), ('ice_espresso', 'Ice Espresso'), ('frappes', 'Frappes'), ('alternatives', 'Hot & Cold Alternatives'), ('milkshakes', 'Milkshakes'), ('lassi', 'Lassi'), ('matcha', 'Matcha'), ('juices', 'Fresh Juices'), ('tea', 'Tea'), ('salads', 'Salads'), ('gravy', 'Gravy with Rice'), ('rice_bowl', 'Rice Bowl'), ('veg_snacks', 'Veg Snacks'), ('nonveg_snacks', 'Non-Veg Snacks'), ('specials', "Chef's Specials"), ('sizzler', 'Sizzler'), ('burgers', 'Burgers & Sandwiches'), ('chowmien', 'Chowmein & Thukpa'), ('noodles', 'Noodles'), ('pizza', 'Pizza'), ('pasta', 'Pasta'), ('momo', 'MO:MO')], default='', help_text='Required for Bar, Café, and Food items to place them in the right section.', max_length=20),
        ),
    ]
